version: '3.9'

networks:
  artion_contracts_network:
    driver: bridge

services:
  ganache-cli:
    build:
      context: ./ganache-cli
    environment:
      - CUSTOM_START_PARAMS=${GANACHE_START_PARAMS:-""}
    ports:
      - ${GANACHE_HOST_PORT:-8545}:8545
    networks:
      - artion_contracts_network
  brownie:
    build:
      context: ./brownie
    command: tail -f /dev/null
    volumes:
      - ../contracts:/home/user/artion/contracts
      - ../interfaces:/home/user/artion/interfaces
      - ../scripts:/home/user/artion/scripts
      - ../tests:/home/user/artion/tests
      - ../build:/home/user/artion/build
      - ../reports:/home/user/artion/reports
    networks:
      - artion_contracts_network